services:
    db:
        container_name: database
        image: 'pgvector/pgvector:pg17'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        env_file:
            - .env
        volumes:
            - 'db_data:/var/lib/postgresql/data'
            - './initpgvector.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - net
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
        user: "${UID}:${GID}"
    app:
        container_name: app_py
        image: 'python:3.11-bullseye'
        env_file:
            - .env
        volumes:
            - './python:/app:delegated'
            - '.env:/app/.env'
        working_dir: /app
        command: tail -f /dev/null
        networks:
            - net
        depends_on:
            - db
        tty: true
        user: "${UID}:${GID}"
networks:
    net:
        driver: bridge
volumes:
    db_data:
        driver: local
